parameters:
- name: 'prefix'
  type: string
  default: 'sgiape'
- name: 'azureServiceConnectionName'
  type: string
  default: 'Terraform-SPN'
- name: 'environmentName'
  type: string
  default: 'dev'
- name: 'path'
  type: string
  default: 'src/01-iac'
- name: 'varFile'
  type: string
  default: 'vars_uat_europe.tfvars'

jobs:
  - job: tf_planing_${{ parameters.environmentName }}
    displayName: Plan Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download CI Artifact
      inputs:
        source: 'current'
        artifactName: terraform-validate-${{ parameters.environmentName }}
        targetPath: $(Pipeline.Workspace)/terraform-src
    - task: AzureCLI@2
      displayName: Terraform Plan
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnectionName }}
        scriptType: pscore
        scriptPath: $(Pipeline.Workspace)/terraform-src/src/tf.ps1
        addSpnToEnvironment: true
        arguments: -Plan -Force -DownloadTerraform -Prefix "${{ parameters.prefix }}" -EnvironmentName "${{ parameters.environmentName }}" -TargetPath "$(Pipeline.Workspace)/terraform-src/${{ parameters.path }}" -VarFile "$(Pipeline.Workspace)/terraform-src/${{ parameters.varFile }}"
    - publish: $(Pipeline.Workspace)/terraform-src/${{ parameters.path }}/terraform.tfplan
      artifact: terraform-plan-${{ parameters.environmentName }}